baseURL = "http://example.com/"
languageCode = "en-us"
title = "hugo-embed-pdf"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "Shortcode to embed PDF files in Hugo sites."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/demo/"
    name = "Demo"
    weight = 2



# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:anvith3@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/opensourcegreasemonkey/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/anvith3/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/anvithks/"
    name = "linkedin"
    weight = 4

